import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'responsive-table-presenter',
  template: `
  <responsive-table-view [list]="list" ></responsive-table-view>
  `,
})
export class ResponsiveTablePresenter implements OnInit {

  list: any[];

  constructor() { }

  TESTDATA = [
    {
      "coilFinalDataId": 14,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 13,
      "entryThickUm": null,
      "lengthM": 3582,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/10/10   15:38:01",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 81791,
      "pdw": null,
      "preparingTime": null,
      "stoppingTime": null
    },
    {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    }, {
      "coilFinalDataId": 9,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 17,
      "entryThickUm": null,
      "lengthM": 2,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/09/29   12:01:28",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 142,
      "preparingTime": 90,
      "stoppingTime": null
    },
    {
      "coilFinalDataId": 4,
      "coilId": 4,
      "scheduleNum": "2",
      "rowNum": "52",
      "coilNumber": 1598069000,
      "cutType": "2 : 1",
      "seqType": null,
      "widthMm": 2,
      "weightKg": 26,
      "entryThickUm": null,
      "lengthM": 777,
      "diameterMm": 52,
      "desStatus": "??? ????? ?????",
      "teamNo": "A",
      "shiftNo": "1",
      "fatherName": 1598069000,
      "producedTime": "1399/08/14   09:26:09",
      "actualWeight": false,
      "name": "ACTR",
      "spiral": false,
      "passCount": null,
      "orderNumber": null,
      "manufacturer": null,
      "finalUsage": null,
      "inputDegree": null,
      "steelGrade": "???? A",
      "rollTimeMin": 0,
      "pdw": 141,
      "preparingTime": 55,
      "stoppingTime": 50
    }
  ]
  ngOnInit() {
    this.list = this.TESTDATA
  }


}
